import React, { useState } from 'react';
import { api } from '../../api';
import useBodyScrollLock from '../../hooks/useBodyScrollLock';

export default function AIReviewModal({ caseItem, onClose, onReviewSuccess, smsUser }) {
  useBodyScrollLock();
  const [decision, setDecision] = useState('APPROVED'); // 'APPROVED' | 'REVISION_NEEDED'
  const [finalFeedback, setFinalFeedback] = useState('');
  const [revisedPrompt, setRevisedPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    setLoading(true);
    try {
      const finalStatus = decision === 'APPROVED' ? 'Completed' : 'Revision Needed';
      const feedbackText = finalFeedback || (
        decision === 'APPROVED' 
          ? 'SMS Specialist evaluated and validated the Lex AI synthesis. Precedents and statutory points approved for final drafting.'
          : 'SMS Specialist requested modifications. Please review notes and re-run revised prompt in Lex AI.'
      );

      await api.finalReviewCase(caseItem.id, {
        finalStatus,
        finalFeedback: feedbackText,
        revisedPrompt: decision === 'REVISION_NEEDED' ? revisedPrompt : undefined,
        reviewerInfo: smsUser ? {
          name: `${smsUser.firstName} ${smsUser.lastName}`,
          position: smsUser.position,
          smsId: smsUser.smsId,
          profileImage: smsUser.profileImage
        } : null
      });

      onReviewSuccess();
      onClose();
    } catch (err) {
      setError(err.message || 'Failed to submit evaluation');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="modal-window modal-window-lg"
        style={{ padding: '2rem 2.25rem' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          borderBottom: '1px solid var(--border-subtle)',
          paddingBottom: '1.25rem',
          marginBottom: '1.5rem'
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.25rem' }}>
              <span style={{ fontSize: '1.4rem' }}>🤖</span>
              <h2 style={{ fontSize: '1.4rem' }}>
                SMS Evaluation of Lex AI Synthesis
              </h2>
              <span className="badge badge-ai">
                {caseItem.id}
              </span>
            </div>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
              Client: <strong style={{ color: 'var(--text-main)' }}>{caseItem.clientName}</strong> | 
              Category: <strong style={{ color: 'var(--accent-cyan)' }}>{caseItem.category}</strong>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{
              background: 'none',
              border: 'none',
              color: 'var(--text-muted)',
              fontSize: '1.75rem',
              cursor: 'pointer',
              lineHeight: 1
            }}
          >
            &times;
          </button>
        </div>

        {error && (
          <div style={{
            background: 'rgba(239, 68, 68, 0.15)',
            border: '1px solid rgba(239, 68, 68, 0.3)',
            color: '#f87171',
            padding: '0.75rem 1rem',
            borderRadius: 'var(--radius-sm)',
            fontSize: '0.85rem',
            marginBottom: '1.25rem'
          }}>
            {error}
          </div>
        )}

        {/* Prompt Used */}
        <div style={{ marginBottom: '1.25rem' }}>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-dim)', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.35rem' }}>
            Original Prompt Provided by SMS
          </div>
          <div style={{
            background: 'rgba(0,0,0,0.3)',
            border: '1px solid var(--border-subtle)',
            padding: '0.75rem 1rem',
            borderRadius: 'var(--radius-sm)',
            fontFamily: 'monospace',
            fontSize: '0.85rem',
            color: '#cbd5e1'
          }}>
            {caseItem.lexPrompt}
          </div>
        </div>

        {/* AI Output Generated by CMS Client */}
        <div style={{ marginBottom: '1.5rem' }}>
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '0.35rem'
          }}>
            <div style={{ fontSize: '0.75rem', color: '#c084fc', textTransform: 'uppercase', fontWeight: 700 }}>
              Lex AI Generated Analysis (Submitted by CMS Client)
            </div>
            <span className="badge badge-ai" style={{ fontSize: '0.65rem' }}>Under SMS Review</span>
          </div>

          <div style={{
            background: 'rgba(10, 20, 29, 0.95)',
            border: '1px solid rgba(139, 92, 246, 0.3)',
            padding: '1.25rem',
            borderRadius: 'var(--radius-md)',
            fontFamily: 'monospace',
            fontSize: '0.88rem',
            lineHeight: 1.6,
            color: '#e2e8f0',
            maxHeight: '260px',
            overflowY: 'auto',
            whiteSpace: 'pre-wrap'
          }}>
            {caseItem.lexOutput || 'No AI output recorded yet.'}
          </div>
        </div>

        {/* Evaluation Decision Form */}
        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          
          <div className="form-group">
            <label className="form-label" style={{ color: 'var(--text-main)' }}>
              Specialist Decision (Approve or Suggest Sudhar / Revisions)
            </label>
            <div style={{ display: 'flex', gap: '1rem' }}>
              <button
                type="button"
                className="btn"
                style={{
                  flex: 1,
                  padding: '0.85rem',
                  background: decision === 'APPROVED' ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)' : 'rgba(255,255,255,0.03)',
                  border: `1px solid ${decision === 'APPROVED' ? 'transparent' : 'var(--border-subtle)'}`,
                  color: '#fff',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '0.5rem'
                }}
                onClick={() => setDecision('APPROVED')}
              >
                <span>✓</span> Final Approval & Case Resolution
              </button>

              <button
                type="button"
                className="btn"
                style={{
                  flex: 1,
                  padding: '0.85rem',
                  background: decision === 'REVISION_NEEDED' ? 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)' : 'rgba(255,255,255,0.03)',
                  border: `1px solid ${decision === 'REVISION_NEEDED' ? 'transparent' : 'var(--border-subtle)'}`,
                  color: '#fff',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '0.5rem'
                }}
                onClick={() => setDecision('REVISION_NEEDED')}
              >
                <span>⚠</span> Suggest Sudhar / Changes Required
              </button>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">
              Specialist Feedback Notes for CMS Client
            </label>
            <textarea
              className="textarea-control"
              rows="3"
              placeholder={decision === 'APPROVED' ? 'e.g. Legal citations and precedent analysis verified. Approved for formal filing.' : 'Explain what improvements or corrections are required in the AI output...'}
              value={finalFeedback}
              onChange={e => setFinalFeedback(e.target.value)}
            ></textarea>
          </div>

          {decision === 'REVISION_NEEDED' && (
            <div className="form-group" style={{ animation: 'fadeIn 0.25s ease-out' }}>
              <label className="form-label" style={{ color: 'var(--accent-amber)' }}>
                Revised AI Prompt for CMS (Optional)
              </label>
              <textarea
                className="textarea-control"
                rows="3"
                placeholder="Specify revised prompt guidelines for the CMS client to re-run in Lex AI..."
                value={revisedPrompt}
                onChange={e => setRevisedPrompt(e.target.value)}
                style={{ fontFamily: 'monospace', borderColor: 'rgba(245, 158, 11, 0.4)' }}
              ></textarea>
            </div>
          )}

          {/* Actions */}
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            borderTop: '1px solid var(--border-subtle)',
            paddingTop: '1.25rem',
            marginTop: '0.5rem'
          }}>
            <button
              type="button"
              className="btn btn-secondary"
              onClick={onClose}
            >
              Cancel
            </button>

            <button
              type="submit"
              className={`btn ${decision === 'APPROVED' ? 'btn-primary' : 'btn-emerald'}`}
              disabled={loading}
              style={{
                padding: '0.85rem 1.75rem',
                background: decision === 'APPROVED' ? 'linear-gradient(135deg, #10b981 0%, #059669 100%)' : 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)'
              }}
            >
              {loading ? 'Submitting...' : decision === 'APPROVED' ? 'Complete & Send Final Approval ➔' : 'Send Sudhar / Revision Request ➔'}
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
